### ISSUE TITLE
Show grid

### ISSUE THREAD

**Issue by LeoKhariton** [ziotom78/gplotpp#14]
Is it possible to draw a grid on the axes?

**Comment by ziotom78** [comment]
Hi Leo, there is no high-level method to draw a grid, but in these cases you can send direct commands to Gnuplot using the `sendcommand` method:

```c++
#include <vector>
#include "gplot++.h"

using namespace std;

int main() {
  vector y{1.0, 3.0, 9.0, 6.0, 5.0, 11.0};
  Gnuplot plt{};
  plt.plot(y);
  plt.sendcommand("set grid ytics lt 2 lw 1");
  plt.show();
}
```

![test](https://github.com/user-attachments/assets/b70062fa-3279-4658-ba2f-897426a4b262)

See [Gnuplot's documentation](https://gnuplot.sourceforge.net/docs_4.2/node188.html) for the parameters to be passed to `set grid`.
